export const dashboard_contents = [
  {
    title: "Compagnie",
    path: "/dashboard/company",
    text: "Éditer les informations générales de la compagnie",
    width: "90%",
    url: "illustration_08_src-pexel.jpg",
  },
  {
    title: "Utilisateurs",
    path: "/dashboard/users",
    text: "Éditer les informations et les rôles des utilisateurs",
    width: "30%",
    url: "illustration_07_src-pexel.jpg",
  },
  {
    title: "Spectacles",
    path: "/dashboard/plays",
    text: "Créer et éditer les informations sur les spectacles",
    width: "30%",
    url: "illustration_01_src-pexel.webp",
  },
  {
    title: "Spectacles sur-mesure",
    path: "/dashboard/taylored_plays",
    text: "Créer et éditer les informations sur les spectacles sur-mesure",
    width: "30%",
    url: "illustration_02_src-pexel.webp",
  },
  {
    title: "Artistes",
    path: "/dashboard/artists",
    text: "Créer et éditer les informations sur les artistes",
    width: "30%",
    url: "illustration_05_src-pexel.jpeg",
  },
  {
    title: "Partenaires",
    path: "/dashboard/partners",
    text: "Créer et éditer les informations sur les partenaires",
    width: "30%",
    url: "illustration_09_src-pexel.jpg",
  },
  {
    title: "Historique",
    path: "/dashboard/stories",
    text: "Créer et éditer l'historique de la compagnie",
    width: "30%",
    url: "illustration_10_src-pexel.jpg",
  },
];
