export interface AhCard {
  "pack_code": "core",
  "pack_name": "Boîte de Base",
  "type_code": "asset",
  "type_name": "Soutien",
  "faction_code": "seeker",
  "faction_name": "Chercheur",
  "position": 41,
  "exceptional": false,
  "myriad": false,
  "code": "01041",
  "name": "Disque d'Itzamna",
  "real_name": "Disc of Itzamna",
  "subname": "Amulette Protectrice",
  "cost": 3,
  "text": "[reaction] Quand un ennemi non-[[Élite]] est généré dans votre lieu, défaussez le Disque d'Itzamna : défaussez cet ennemi.",
  "real_text": "[reaction] When a non-[[Elite]] enemy spawns at your location, discard Disc of Itzamna: Discard that enemy.",
  "quantity": 1,
  "skill_willpower": 1,
  "skill_intellect": 1,
  "skill_combat": 1,
  "xp": 2,
  "health_per_investigator": false,
  "deck_limit": 2,
  "slot": "Accessoire",
  "real_slot": "Accessory",
  "traits": "Objet. Relique.",
  "real_traits": "Item. Relic.",
  "flavor": "Le craignent-ils à cause de ce qu'il leur ferait ? Ou le craignent-ils à cause de ce qu'il vous ferait ?",
  "illustrator": "Melissa Findley",
  "is_unique": true,
  "permanent": false,
  "double_sided": false,
  "octgn_id": "f744ace1-c5bc-4641-b634-34efb8d52aaf",
  "url": "https://fr.arkhamdb.com/card/01041",
  "imagesrc": "/bundles/cards/01041.png",
  "duplicated_by": [
    "01541"
  ]
}